[package]
name = "loxide"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "^0.5.1"

[[bench]]
name = "fibonacci"
harness = false

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false


[features]
debug = []
